dist: bionic
language: python
group: edge

python:
  - "3.8"

services:
  - docker
  - redis

addons:
  apt:
    packages:
      - python3-setuptools
      - python3-pip
      - python3-openssl
      - python3-wheel
      - python3-numpy

before_install:
  - pip3 install --upgrade pip

install:
  - pip3 install .

before_script:
  - echo $(pwd)

  - export PYTHONPATH=$PYTHONPATH:$(pwd):$(pwd)/libsvc
  # Create an orthanc service (want to do this with a fixture later, I suspect)
  - docker run --rm -d -p 8042:8042 derekmerck/orthanc-cwbv

  - mkdir -p ~/data/dcm && pushd ~/data/dcm
  - curl https://repository.library.brown.edu/viewers/archive/bdr:697313/download -L -o ibis1.zip
  - curl https://repository.library.brown.edu/viewers/archive/bdr:697314/download -L -o ibis2.zip
  - unzip -j ibis1.zip -d ibis1 && rm ibis1.zip
  - unzip -j ibis2.zip -d ibis2 && rm ibis2.zip
  - popd
  - echo $(cwd)

  - cd $TRAVIS_BUILD_DIRECTORY

script:
  - pytest

after_success:
  - DIANA_VERSION=$(python3 -c "import diana; print(diana.__version__)")
  # Login to docker for push
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Update diana image
  - cd docker
  - docker build . -t "${DOCKER_USERNAME}/diana3" --label version=${DIANA_VERSION}
  - docker push "${DOCKER_USERNAME}/diana3"
